#!/bin/bash

croc send --code wack-abce test.txt &

sleep 2

curl -X POST \
  '192.168.1.69:8080/sendFile' \
  --header 'Accept: */*' \
  --header 'User-Agent: Thunder Client (https://www.thunderclient.com)' \
  --header 'Content-Type: application/json' \
  --data-raw '{
    "SC_API_Key" : "ServerClientAPIKey",
	"O_API_Key" : "OragnizationAPIKey",
	"CO_API_Key" : "ClientOrganizationKey",
	"code-phrase" : "wack-abce"
}'